### ISSUE TITLE
Set up DNS name for API Gateway to keep URL consistent

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/rialto#222]
Currently the name is assigned by Terraform/AWS upon creation. We might consider setting this up ourselves?

https://www.terraform.io/docs/providers/aws/guides/serverless-with-aws-lambda-and-api-gateway.html#custom-domain-names-and-tls-certificates

**Comment by aaron-collier** [comment]
Looks like in the doc above we need to setup a TLS certificate in order to establish the route53 record specifically for the API gateway. We should shedule some time to walk through this ith @jonrober, @tingulfsen, and @aaron-collier

**Comment by jonrober** [comment]
Reading through that, we either get the cert from ACM or our own Stanford process.  In the latter case it's a matter of setting the record up in netdb for whatever hostname you want.  The netdb record won't actually be used for DNS resolution since that goes to Route53, but is needed as verification for the backend that UIT uses to verify the requester has the right to request a cert for that hostname.

In the former case it's doing what we already do in other places in Terraform.   The simplest I can see is in organizations/production/infrastructure, under the Certificates section.  Then after that's set up, use the second example in the first section in https://www.terraform.io/docs/providers/aws/r/api_gateway_domain_name.html.

Using route53 makes it all a bit easier, though means that we can't get at the cert if we need to put it on a server as well.  That doesn't seem to matter for this case.

**Comment by aaron-collier** [comment]
Since we are using this link for internal ETL and not currently for external access, we can close this at this time.
