### ISSUE TITLE
Solr is not committing

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto#316]
See the 🚫 in this image?
<img width="296" alt="screen shot 2018-11-08 at 7 47 01 am" src="https://user-images.githubusercontent.com/92044/48202456-8be56b80-e32a-11e8-9d1b-cb3231183883.png">

This indicates there are docs that are not committed to disk.

Let's add this to the update handler (https://github.com/sul-dlss/rialto-webapp/blob/master/solr/conf/solrconfig.xml#L13-L17): 
```
    <autoCommit>
      <maxTime>15000</maxTime>
      <openSearcher>false</openSearcher>
    </autoCommit>
```
This is how the default solr schema works. See https://github.com/apache/lucene-solr/blob/master/solr/example/files/conf/solrconfig.xml#L301-L304

**Comment by aaron-collier** [comment]
Fixed in dev. Will mirror in staging and production.

![Screen Shot 2018-11-15 at 8.28.28 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c1c675031c9f00120c29b9/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f66b7191a370f110234f5d575edd3c4a4356bcbbd671f3e57862804e0ee5d865097dc56e12f9e9821abc04b3208a1984b2b98a48d2f42f67b6d5db1063474f4dcbed5727a19e41c95df249e3445ca7103366e3722431.png)
