### ISSUE TITLE
Jena - Vitro Inferencing Trigger

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#44]
When working against Jena directly, how is inferencing in Vitro triggered?

**Comment by mjgiarlo** [comment]
Loaders that are not Vitro-based (such as a Jena API loader) will need to be followed by triggering a manual recomputation of inferences. To do this manually, click the "Recompute Inferences" link in the admin UI or hit it via https://rialto-vitro-dev.stanford.edu/vitro/RecomputeInferences, but note that you can't just curl that URL because 1) you will be challenged by Shibboleth first, and then 2) you need to be logged in to Vitro.
