### ISSUE TITLE
Jena - Vitro Indexing Trigger

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#45]
When working against Jena directly, how is Vitro indexing triggered?

**Comment by mjgiarlo** [comment]
Loaders that are not Vitro-based (such as a Jena API loader) will need to be followed by triggering a manual reindex. To manually reindex Vitro, click the "Rebuild Search Index" link in the admin UI or hit it via https://rialto-vitro-dev.stanford.edu/vitro/SearchIndex?rebuild=1, but note that you can't just curl that URL because 1) you will be challenged by Shibboleth first, and then 2) you need to be logged in to Vitro.
