### ISSUE TITLE
Vitro "Pause" Function for Indexing?

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#46]
Does Vitro codebase (or where in the vitro codebase) is the indexing "pause" function?

**Comment by mjgiarlo** [comment]
Here are the method definitions within Vitro that make the search indexer pauseable and unpauseable:

https://github.com/vivo-project/Vitro/blob/608aa1cf54648f35045eb1ec717b143269b11273/api/src/main/java/edu/cornell/mannlib/vitro/webapp/searchindex/SearchIndexerImpl.java#L195-L224

And you can see the SPARQL Update API controller use the API here: https://github.com/vivo-project/Vitro/blob/ff71245de1394cc2e3e0474d78300e6c5ca2f339/api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/api/SparqlUpdateApiController.java#L105-L121

**Comment by mjgiarlo** [comment]
As far as I know this is not exposed in the HTTP API, so loaders that are not Vitro-based will need to be followed by triggering a manual reindex. To manually reindex Vitro, click the "Rebuild Search Index" link in the admin UI or hit it via https://rialto-vitro-dev.stanford.edu/vitro/SearchIndex?rebuild=1, but note that you can't just curl that URL because 1) you will be challenged by Shibboleth first, and then 2) you need to be logged in to Vitro.
