### ISSUE TITLE
Enumerate options in BlazeGraph for triggering solr index build

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#79]

**Comment by tingulfsen** [comment]
Blazegraph comes with support for Solr:

https://wiki.blazegraph.com/wiki/index.php/ExternalFullTextSearch

**Comment by tingulfsen** [comment]
In order to actually trigger a Solr (or other external data store/index) build or update, Blazegraph provides a "Change Listener" (that we could use to build our own pub/sub mechanism):

https://sourceforge.net/p/bigdata/discussion/676946/thread/0453f06e/?limit=25

https://wiki.blazegraph.com/wiki/index.php/FederatedQuery#Custom_Services

https://blazegraph.github.io/database/apidocs/com/bigdata/rdf/changesets/IChangeLog.html

See generally

https://wiki.blazegraph.com/wiki/index.php/Code_Examples

**Comment by jcoyne** [comment]
I don't think there's anything useful here beyond "In theory it could be done"  The page that tells you how to do it (https://wiki.blazegraph.com/wiki/index.php/FederatedQuery#Monitoring_Updates) points at a bunch of dead links (I suspect http://bigdata.com/ was sold off when SYSTAP was dissolved)

**Comment by jcoyne** [comment]
After getting on a call with Mike and Tommy, the conclusion we came to was that, there is no "out of the box" way to publish changes to a channel.  We probably could, given enough time, figure out how to fork the Blazegraph code so that we could register a listener for updates.  However there is no documentation showing how to do this and as Blazegraph development stopped 2 years ago, we don't expect we'd find much support if we run into difficulties.   Additionally we have no idea as to how such a change would impact performance or stability of Blazegraph. 

An alternative and much simpler approach would be to publish our changes to a channel and have a listener subscribe to the channel and push changes to blazegraph and then notify the indexer to rebuild.
