### ISSUE TITLE
Document how Combine SPARQL Loader will integrate with RIALTO Core

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#98]
How will the end of our pipeline write data to that SPARQL update endpoint

**Comment by jcoyne** [comment]
@cmh2166 can we say this is closed by sul-dlss-labs/rialto-api#17

**Comment by mjgiarlo** [comment]
@jcoyne I believe this ticket requires some changes on the ETL/pipeline side. Our prototype ETL tool currently extracts and transforms only -- it doesn't have any loaders built and we'll need a loader to integrate that tool (or a different implementation of the pipeline) with the rialto-api endpoint.

**Comment by mjgiarlo** [comment]
Correction to my comment above: this issue is closed when we document *how* the Combine will access RIALTO Core, including any steps related to AWS security, authorization, etc.

**Comment by mjgiarlo** [comment]
In order to close this, we need to decide how we're going to secure and authorize access to the SPARQL Loader lambda. More on the ways available to us here: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-to-api.html

(And we should use the same authorization scheme for the trigger rebuild lambda.)

**Comment by mjgiarlo** [comment]
I added authorization to both of our APIs and documented it here: https://github.com/sul-dlss/rialto/wiki/RIALTO-Combine-Core-Integration
